"""
Django settings for mpesa_backend project.

Generated by 'django-admin startproject' using Django 4.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-3w)du5q*9#%5%o!ed%mpg9$!79t&658$qe-ar)*tgc-2ca=cmw'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False



import os

# MPESA_CONFIGS = {
#     "CONSUMER_KEY": os.getenv("MPESA_CONSUMER_KEY"),
#     "CONSUMER_SECRET": os.getenv("MPESA_CONSUMER_SECRET"),
#     "SHORTCODE": os.getenv("MPESA_SHORTCODE", "600998"),  # Use test shortcode
#     "PASSKEY": os.getenv("MPESA_PASSKEY", "YOUR_PASSKEY_HERE"),
#     "CALLBACK_URL": os.getenv("MPESA_CALLBACK_URL", "https://derivgo-backend.onrender.com//callback"),
#     "ENVIRONMENT": os.getenv("MPESA_ENVIRONMENT", "sandbox"),  # Keep as 'sandbox' for testing
# }
import environ

env = environ.Env()
environ.Env.read_env()  # Reads the .env file

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Take environment variables from .env file
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))
MPESA_CONFIGS = {
    'CONSUMER_KEY': env('MPESA_CONSUMER_KEY'),
    'CONSUMER_SECRET': env('MPESA_CONSUMER_SECRET'),
    'BUSINESS_SHORT_CODE': env('MPESA_BUSINESS_SHORT_CODE'),
    'PASS_KEY': env('MPESA_PASS_KEY'),
    'TRANSACTION_TYPE': env('MPESA_TRANSACTION_TYPE'),
    'CALLBACK_URL': env('MPESA_CALLBACK_URL'),
}




# Application definition



INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'payments', 
    'corsheaders',
    
]
ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    'e894-102-0-16-50.ngrok-free.app', 
    'derivgo-backend.onrender.com',
    'theblacksamurai.site'
]

CORS_ALLOW_CREDENTIALS = True

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware'

]
CSRF_TRUSTED_ORIGINS = [
    "https://e894-102-0-16-50.ngrok-free.app",
    "https://derivgo-backend.onrender.com",
    "https://theblacksamurai.site",
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "https://e894-102-0-16-50.ngrok-free.app",
    "https://derivgo-backend.onrender.com",
    "https://theblacksamurai.site"
]


CORS_ALLOW_ALL_ORIGINS = True

CORS_ALLOW_METHODS = [
    "GET",
    "POST",
    "PUT",
    "PATCH",
    "DELETE",
    "OPTIONS"
]

CORS_ALLOW_HEADERS = [
    "content-type",
    "authorization",
    "x-requested-with"
]
ROOT_URLCONF = 'mpesa_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mpesa_backend.wsgi.application'

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',  # Correct usage of Path object
    }
}

# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']  # Correct usage of Path object
# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
